### ISSUE TITLE
Use openwrt 

### ISSUE THREAD

**Issue by arashmh13** [nasnet-community/solutions#1]
Hey
U can use openwrt for your project 
Openwrt supporting lots of routers (not just one tp link router), its critical downside of your project. 
Also there is a powerful vpn app called passwall for openwrt, which cover all types of vpn like v2ray, wireguard and ...( for hiding real ip)
Plus, you can use rules future of passwall for routinng domestic adress and ip

You just need to change some little thing and rules on openwrt to use 2 modem internet (domestic modem and starlink) at the same time!

Idea behind of your project is brilliant 👏 
I see very successful project If you try to improve it 

Useful link for you:
https://github.com/xiaorouji/openwrt-passwall2
https://github.com/amirhosseinchoghaei/Passwall

**Comment by markpash** [comment]
Hi @arashmh13 ❤️ the NeighborLink project does in fact use OpenWRT. Currently there's only one tested/supported device but I'm sure that many more will be added to the list.

Passwall is a fantastic project and it may be used in the future. Thanks for providing the links. 🫶
